site_name: NHS Federated Data Platform Design guide
# site_url: https://example.com
repo_url: https://github.com/baracoffice/pagetest
repo_name: Design guide page test
edit_uri: edit/main/docs/
plugins:
  - search
nav:
  - Home: index.md

theme:
  name: material
#   custom_dir: overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Arial
  logo: images/logo/nhs-blue-on-white.jpg
  favicon: images/favicon/favicon.ico
